version: '3.6'

services:
  sintrop-app:
    container_name: SINTROP-OS-APPS
    command: ["sleep", "infinity"]
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8547:8547
      - 5002:5002
      - 8082:8082
    networks: 
      - app-tunnel
    volumes: 
      - ./:/app
  eth-security-toolbox:
    container_name: ETH-SECURITY-TOOLBOX2
    image: trailofbits/eth-security-toolbox
    networks: 
      - app-tunnel
networks: 
  app-tunnel:
    driver: bridge
